pull_request_rules:
  - name: alpha
    conditions:
      - base=alpha
      - label=ready-to-merge
    actions:
      delete_head_branch:
        force: true
      merge:
        method: merge
        strict: smart
  - name: beta
    conditions:
      - base=beta
      - label=ready-to-merge
    actions:
      delete_head_branch:
        force: true
      merge:
        method: merge
        strict: smart
  - name: master
    conditions:
      - base=master
      - label=ready-to-merge
    actions:
      delete_head_branch:
        force: true
      merge:
        method: merge
        strict: smart
