name: Auto Approve
on: pull_request
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        if: github.actor == 'shunkakinoki'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.createReview({
              pull_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: 'APPROVE',
            })
      - uses: actions/github-script@0.9.0
        if: |
          github.actor == 'github-actions[bot]' ||
          github.actor == 'dependabot[bot]' ||
          github.actor == 'dependabot-preview[bot]' ||
          github.actor == 'imgbot' ||
          github.actor == 'imgbot[bot]'
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            github.pulls.createReview({
              pull_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: 'APPROVE',
            })
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  ready:
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        if: |
          github.event.pull_request != null && contains(toJson(github.event.pull_request.title), '[sentrei-auto-pr]') && (github.actor == 'shunkakinoki') ||
          github.actor == 'dependabot[bot]' ||
          github.actor == 'dependabot-preview[bot]' ||
          github.actor == 'mergify[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          msg: "/ready"
