name: Terraform
on: pull_request
jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [master]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: fmt
          tf_actions_working_dir: infrastructure/environments/${{ matrix.environment }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: init
          tf_actions_working_dir: infrastructure/environments/${{ matrix.environment }}
        env:
          TF_CLI_ARGS_init: '-backend-config="token=${{ secrets.TF_API_TOKEN }}" -backend-config="organization=vapras"'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: validate
          tf_actions_working_dir: infrastructure/environments/${{ matrix.environment }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
